
-- Rol 1: solo lectura sobre todo el modelo.
CREATE ROLE ROL_CONSULTA_FIFA_G2;

GRANT SELECT ON EDICION_MUNDIAL       TO ROL_CONSULTA_FIFA_G2;
GRANT SELECT ON ESTADIO               TO ROL_CONSULTA_FIFA_G2;
GRANT SELECT ON SELECCION             TO ROL_CONSULTA_FIFA_G2;
GRANT SELECT ON PARTIDO               TO ROL_CONSULTA_FIFA_G2;
GRANT SELECT ON PARTICIPACION_PARTIDO TO ROL_CONSULTA_FIFA_G2;
GRANT SELECT ON ASISTENCIA_PARTIDO    TO ROL_CONSULTA_FIFA_G2;

-- Rol 2: registra partidos y participaciones, sin administrar catalogos ni poder borrar resultados ya registrados.
CREATE ROLE ROL_OPERATIVO_FIFA_G2;

GRANT SELECT ON EDICION_MUNDIAL TO ROL_OPERATIVO_FIFA_G2;
GRANT SELECT ON ESTADIO         TO ROL_OPERATIVO_FIFA_G2;
GRANT SELECT ON SELECCION       TO ROL_OPERATIVO_FIFA_G2;

GRANT SELECT, INSERT, UPDATE ON PARTIDO               TO ROL_OPERATIVO_FIFA_G2;
GRANT SELECT, INSERT, UPDATE ON PARTICIPACION_PARTIDO TO ROL_OPERATIVO_FIFA_G2;
GRANT SELECT, INSERT, UPDATE ON ASISTENCIA_PARTIDO    TO ROL_OPERATIVO_FIFA_G2;


GRANT ROL_CONSULTA_FIFA_G2  TO is101010;//pablo
GRANT ROL_OPERATIVO_FIFA_G2 TO is101002; // julian 

-- Demostracion de REVOKE (ver tests/pruebas_privilegios.md).
REVOKE UPDATE ON PARTIDO FROM ROL_OPERATIVO_FIFA_G2;
GRANT UPDATE ON PARTIDO TO ROL_OPERATIVO_FIFA_G2;

-- Verificacion de lo otorgado.
SELECT role, table_name, privilege
FROM ROLE_TAB_PRIVS
WHERE role IN ('ROL_CONSULTA_FIFA_G2', 'ROL_OPERATIVO_FIFA_G2')
ORDER BY role, table_name, privilege;